_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  BACKBONE:
    NAME:  "build_ASTModel_backbone_fpn"
  AST:
    PRETRAINED_MODEL: "MIT/ast-finetuned-audioset-10-10-0.448-v2"
  DiffusionDet:
    HIDDEN_DIM: 256
    NUM_PROPOSALS: 20
    NUM_CLASSES: 2
  EMA_ENABLED: False
DATASETS:
  TRAIN: ("ami_train",)
  # EVAL: ("ami_val",)
  TEST:  ("ami_test",)
INPUT:
  SAMPLING_RATE: 16000
  SECONDS_PER_SEGMENT: 10 #30
  TOT_BATCH_SIZE: 2
  NUM_WORKERS: 1
